# Generated by Django 4.0.6 on 2022-07-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_status'),
        ('todo', '0002_alter_todoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_list', to='accounts.account'),
        ),
    ]
