# Generated by Django 4.0.6 on 2022-07-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(upload_to='avtor/')),
                ('bio', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('top', 'top'), ('satisfactory', 'satisfactory'), ('unsatisfied', 'unsatisfied')], max_length=32)),
            ],
        ),
    ]
