# Generated by Django 4.0.6 on 2022-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('top', 'top'), ('satisfactory', 'satisfactory'), ('unsatisfied', 'unsatisfied')], max_length=32, null=True),
        ),
    ]
